### ISSUE TITLE
계절 옵션 추가

### ISSUE THREAD

**Issue by MillionKiwi** [2023-OSS-Team20/Tourist_attraction_Web#12]
계절옵션 추가가 가능한지가 의문임. 받아오는 리스트량이 많아서 계절을 하나하나 추가하기엔 힘들 것 같음. 축제나 장소를 보고 해당 단어가 있으면 계절 추가하는 식으로 해야할 것 같은데 정확히 어떤 방향으로 구현이 가능한지 모르겠음.

이에 대한 대책으로 반려동물 여행정보를 확인하는 기능을 넣는 것에 대해 어떤지?(이는 tourAPI에서 제공되는 기능임) 사이트 내부에 들어가서 버튼을 누르면 반려동물과 같이 입장이 가능한지, 주의할 것이 있는지 등을 알려줌.
커멘트 부탁드림.

**Comment by cmc4647** [comment]
반려동물 좋은 생각인 거 같습니다! 
혹시 숙박 타입은 어떨까요? (민박/ 팬션/ 호텔 등..) 이것 또한 비슷한 문제가 발생할 것 같긴 한데.. 좀 더 고민해보겠습니다!

**Comment by csj0606** [comment]
신중하게 고민을 해봤는데 역시 계절옵션과 같이 자체적으로 태그를 추가하는건 힘들다는 의견에 저도 동의합니다..
그래서 대안으로 생각해 보았는데, 키워드를 자체적으로 만드는 방법이 아니라 tourAPI 사이트의 메인 검색 페이지의 방법을 그대로 가져와 관광지, 문화시설 등등의 관광 타입의 버튼을 만들고 추가로 지역을 선택하여 한번에 검색이 가능하게 만드는 것은 어떨까요?
